tasks:
- name: aws-cli
env:
  AWS CLI AUTO PROMPT: on-partial
init:
cd /workspace
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" o "awscliv2.zip"
unzip awscliv2.zip
sudo ./aws/install
cd $THEIexpoA_WORKSPACE_ROOT
vscode:
  extensions:
    - 42Crunch.vscode-openapi